---
- hosts: WEBSERVER
  remote_user:  provision
 
  tasks:

    - name: install python-software-properties
      apt: pkg=python3 state=installed

    - name: "add nginx ppa if it ubuntu 10.04 and up"
      action: apt_repository repo=ppa:nginx/stable
#      only_if: "$is_ubuntu and $is_10_up"

    - name: update apt repo
      action: apt update-cache=yes

    - name: install nginx 
      action: apt name=nginx state=installed

    - name:  copy fixed init for nginx
      action: copy src=files/nginx.init dest=/etc/init.d/nginx mode=0755  backup=yes
     
    - name: service nginx 
      action: service name=nginx state=started 

    - name: write nginx.conf 
      action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes

#    - name: install postgres
#      apt: pkg=nginx state=installed update_cache=true
    
    - name: install Python 3
      apt: pkg=python3-minimal state=installed

    - name: PHP | install ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: install php
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - php7.0-cli
        - php7.0-mysql
        - php7.0-cgi
        - php7.0-fpm
        - php7.0-gd
        - php7.0-imap
        - php7.0-xml
        - php7.0-mbstring
        - php7.0-intl
        - php7.0-apcu
        - python-pip

    - name: copy web dir
      copy: src={{ item }} dest=/usr/share/nginx/www/{{ item }}
      with_items:
        - 1and1.tar.gz
    - unarchive:
        src: /usr/share/nginx/www/{{ item }}
        dest: /usr/share/nginx/www/
        copy: no
        remote_src: true 
      with_items:
        - 1and1.tar.gz

#- hosts: WEBSERVER
#  remote_user: gdhb
#  tasks:
#    - name: copy index
#      synchronize:
#        mode: pull
#        src: rsync://gdhb@192.168.0.1/home/gdhb/tmp/ 
#        dest: usr/share/nginx/www/ 

- hosts: DATABASE
  remote_user: provision
  tasks:
    - name: install mysql
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client
        - build-essential



  


   
